name: test-workflow

on:
  # This workflow can be called by another workflow
  workflow_call:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: string
        default: "dev"

      project:
        description: "Project name"
        required: true
        type: string
        default: "roboshop"

      component:
        description: "Component name"
        required: true
        type: string
        default: "frontend"

jobs:
  actions-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: List the files
        run: ls -l
